### ISSUE TITLE
feature 消息类型添加 QQ 的 emoji

### ISSUE THREAD

**Issue by Nzzz964** [Drincann/Mirai-js#154]
能否添加 QQ 的 emoji 添加到 MessageType 🤔

大概是这样 https://github.com/Nzzz964/Mirai-js/commit/5f0872080054de6f69226bc18c90f28b1b6b2a93

**Comment by Drincann** [comment]
Looks good but I had some questions.

I thought we had a better time cost solution to build the Face instance, maybe hashtable or enum but not array.

And I found the code in the link you just mentioned like missed something face.

The complete faceid seems to be here -> https://github.com/mamoe/mirai/blob/dev/mirai-core-api/src/commonMain/kotlin/message/data/Face.kt

I thought the enum is better, because not only the time cost lower but also every developer can browsing the whole faces in the code editor but not the string that maybe makes mistake.

**Comment by Drincann** [comment]
PR welcome, ty.

**Comment by Nzzz964** [comment]
> PR welcome, ty.

I created a new PR for adding `Face` message type IDE friendly #155
